version: '3.3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: doan
      MYSQL_USER: admin
      MYSQL_PASSWORD: doan2023
      MYSQL_ROOT_PASSWORD: doan2023
    ports:
      - 3310:3306
    volumes:
      - datadoan:/var/lib/mysql
      - ./doan:/doan
  # mongodb:
  #   image: mongo:latest
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: pimmm2021
  #   volumes:
  #     - datamongodb:/data/db
  #   ports:
  #     - 27017:27017
  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: mongo-express
  #   restart: always
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: pimmm2021
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     ME_CONFIG_MONGODB_PORT: "27017"
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongodb
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: pimmm2021 
  nginx:
    build: ./docker/nginx
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - dataredis:/data
    ports:
      - "6380:6380"
  php:
    build: ./docker/php
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/html
volumes: 
    datadoan:
    dataredis:
    # datamongodb:

